on:
  schedule:
    - cron: '*/5 1,2,3,4 * * *'
    - cron: '12,42 0,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *'

name: Fetch and store

jobs:
  fetch:
    name: Fetch and store
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Scrape
      run: |
        yarn
        node fetch-and-store.js
        node generate-csv.js
    - name: Push data
      run: |
          git config user.name jxeeno
          git config user.email ken+github@jxeeno.com
          git add . || exit 0
          git commit -m "auto(): update data" || exit 0
          git push || exit 0
